import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_DIR = os.path.join(BASE_DIR, "models")

YOLO_WEIGHTS = os.path.join(MODEL_DIR, "yolov4-tiny.weights")
YOLO_CONFIG = os.path.join(MODEL_DIR, "yolov4-tiny.cfg")
COCO_NAMES = os.path.join(MODEL_DIR, "coco.names")

CONFIDENCE_THRESHOLD = 0.15
NMS_THRESHOLD = 0.45
INPUT_SIZE = (416, 416)
CENTER_ONLY_DETECTION = True
DETECTION_CENTER_FRACTION = 0.5

CAMERA_INDEX = 0
VIDEO_WIDTH = 1280
VIDEO_HEIGHT = 720

WINDOW_NAME = "Real-Time Object Detection | YOLOv4-tiny"
SHOW_FPS = True
SHOW_CONFIDENCE = True
SHOW_CLASS_LABEL = True

VOICE_ENABLED = True
VOICE_CONFIDENCE_THRESHOLD = 0.20
VOICE_COOLDOWN = 0.5
VOICE_CENTER_FRACTION = 0.5
VOICE_RATE = 175
VOICE_VOLUME = 1.0

USE_GPU = False
